// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace bus_transport_mgt_sys.Models;

public partial class Bus
{
    [Key]
    public string PlateNo { get; set; }

    public int NoOfSeats { get; set; }

    public string Model { get; set; }

    public int RouteId { get; set; }

    public virtual ICollection<Driver> Drivers { get; set; } = new List<Driver>();

    public virtual Route Route { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}