// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bus_transport_mgt_sys.Models;

public partial class Driver
{
    public int DriverId { get; set; }

    public int UserId { get; set; }

    public string Licence { get; set; }

    public string AssignedBusId { get; set; }

    public virtual Bus AssignedBus { get; set; }

    public virtual User DriverNavigation { get; set; }
}