// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bus_transport_mgt_sys.Models;

public partial class Route
{
    public int RouteId { get; set; }

    public string RouteName { get; set; }

    public string Departure { get; set; }

    public string Destination { get; set; }

    public virtual ICollection<Bus> Buses { get; set; } = new List<Bus>();

    public virtual ICollection<Stop> Stops { get; set; } = new List<Stop>();
}