// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bus_transport_mgt_sys.Models;

public partial class Schedule
{
    public int ScheduleId { get; set; }

    public string BusId { get; set; }

    public DateTime DepartureTime { get; set; }

    public DateTime ArrivalTime { get; set; }

    public int Amount { get; set; }

    public virtual Bus Bus { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}