// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bus_transport_mgt_sys.Models;

public partial class Stop
{
    public int StopId { get; set; }

    public string StopName { get; set; }

    public int RouteId { get; set; }

    public virtual Route Route { get; set; }
}