// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bus_transport_mgt_sys.Models;

public partial class Ticket
{
    public int TicketId { get; set; }

    public string BusId { get; set; }

    public int UserId { get; set; }

    public int ScheduleId { get; set; }

    public virtual Bus Bus { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Schedule Schedule { get; set; }

    public virtual User User { get; set; }
}