// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace bus_transport_mgt_sys.Models;

public partial class User
{
    public int UserId { get; set; }

    [Column("full_name")]
    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string PasswordHash { get; set; }

    public string Role { get; set; } = "User";

    public DateTime CreatedAt { get; set; } = DateTime.Now;

    public bool IsActive { get; set; } = true;

    public virtual Driver Driver { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}